# .github/dependabot.yml
version: 2

multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "weekly-dependencies"
    cooldown:
      default-days: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "weekly-dependencies"
    cooldown:
      default-days: 5
