services:
  get-gov:
    image: node:20-alpine
    platform: linux/amd64
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    command: >
      sh -c "
      apk add --no-cache chromium &&
      rm -rf node_modules package-lock.json &&
      npm cache clean --force &&
      npm install &&
      npm run dev"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  owasp:
    image: ghcr.io/zaproxy/zaproxy:stable
    platform: linux/amd64
    user: "root"
    command: >
      sh -c "
      echo 'Waiting for site to be ready...' &&
      sleep 30 &&
      zap-baseline.py -t http://get-gov:8080 -c zap.conf -I -r zap_report.html"
    volumes:
      - .:/zap/wrk/
    depends_on:
      get-gov:
        condition: service_healthy