title: get.gov
email: registrar@cisagov.gov
description: >-
  The top-level domain for U.S.-based government organizations
twitter: CISAgov

# TODO: Configure Digital Analytics Program
# # Configuration for the Digital Analytics Program
# dap:
#   agency: your-agency
#   subagency: your-subagency

# Configuration for Google Analytics
ga:
  ua: ua-33523145-2

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: Domains
    url: /domains
  - name: Help
    url: /help
  - name: Blog
    url: /blog
  - name: About
    url: /about

# TODO: Registrar url that can be referenced throughout get.gov
registrar:
  url: 
# Add https://getgov-stable.app.cloud.gov back when we're ready to link to the form

# TODO: Implement custom search.gov
searchgov:

#   # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

#   # Replace this with your search.gov account.
  affiliate: .gov

#   # Replace this with your access key.
  access_key: mfC_MRpssyqvgS8kwacKo6ihHmfBcQtZ0R2DtwYKIKw=
    #
#   # This renders the results within the page instead of sending to user to search.gov.
  inline: true

#   # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
#   # If you do not want to present search suggestions, set this value to false.
#   suggestions: true
