name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pa11y-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Use Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 #v3.9.1
        with:
          node-version: '18.x'
      - name: Install node dependencies
        run: npm install
      - name: Accessibility scan
        run: npm run pa11y
